# Generated by Django 4.2.25 on 2026-01-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_audioprediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimagemodel',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
